### ISSUE TITLE
world femine 

### ISSUE THREAD

**Issue by szinter** [rangeoshun/wormer#31]
After a while, no new food were created.
![bug4](https://cloud.githubusercontent.com/assets/295901/14244039/4dfeb91e-fa59-11e5-8c47-948102482096.png)

**Comment by rangeoshun** [comment]
Should be fixed, please confirm.

**Comment by szinter** [comment]
no siting so far. Good job!

**Comment by rangeoshun** [comment]
Cool :) Then it was a sync issue. Sometimes if someone spawned and got a full state update, you might loose a state cycle.
