### ISSUE TITLE
death is among us

### ISSUE THREAD

**Issue by szinter** [rangeoshun/wormer#32]
So after a death my wrom did not despawn. It was only shown in my client  and it acted like the part of the map. It just a graphical bug but still creepy. :P 
![bug5](https://cloud.githubusercontent.com/assets/295901/14244285/91057198-fa5a-11e5-80c7-725a5f5c9ca3.png)

**Comment by rangeoshun** [comment]
Should be fixed, please confirm.

**Comment by szinter** [comment]
It still happens sometimes :/

**Comment by rangeoshun** [comment]
Let's hope this fixes it.

**Comment by rangeoshun** [comment]
This did not fix it! Or it might have, but introduced other issues...

**Comment by rangeoshun** [comment]
Maybe now. There was an if statement which checked aliveness in die() method. This was to prevent users from dieing when dead. This is prohibited somewhere else now, maybe this will solve it. Fingers crossed.

**Comment by rangeoshun** [comment]
Nope, damn it!

**Comment by rangeoshun** [comment]
:(

**Comment by rangeoshun** [comment]
hope to have fixed this. Please confirm.

**Comment by nth-erik** [comment]
Nope, it's Chuck Testa!
![death_among_us_2016-04-13](https://cloud.githubusercontent.com/assets/3939737/14506707/73f5058e-01bf-11e6-8646-b0e7edc7406f.jpg)

**Comment by rangeoshun** [comment]
Sh*t!!

**Comment by nth-erik** [comment]
Cutting own tail (~30000 long) resulted in this glitch.

**Comment by nth-erik** [comment]
It's still doing it... :disappointed: 

**Edit:** Killed myself once, I "shrunk into nothing" - killed myself for the second time, I gained sixth sense - killed myself a third time and I "shrunk" again. Logged in again and it didn't produce the glitch this time (with a short wrom).

**Comment by rangeoshun** [comment]
Argh... someone should fix this bug already!! Wait... I'm the one :D
