### ISSUE TITLE
Inedible food

### ISSUE THREAD

**Issue by nth-erik** [rangeoshun/wormer#39]
I've noticed that some dots are frozen into the screen, and I cannot pick them up (it's not just a visual glitch).

**Comment by rangeoshun** [comment]
hope to have fixed this. Please confirm.

**Comment by nth-erik** [comment]
## NEGATIVE

Problem persists. I could only pick up a mine from the side after failing from the top.

**Comment by rangeoshun** [comment]
That's a warp issue with the map. I thought you refer to the problem where you could not pick up some foods at all.
