### ISSUE TITLE
undefined variable property Exception breaks game

### ISSUE THREAD

**Issue by szinter** [rangeoshun/wormer#44]
Happens around 1000 points 

InvisiblePoint 1540aba2c0d is dead
angular-client.js:660 Point 1540aba565c is alive
angular-client.js:694 Point 1540ab9acdb is dead
angular-client.js:660 PickupMinePoint 1540aba7507 is alive
angular-client.js:2720 Uncaught TypeError: Cannot read property '1' of undefined

**Comment by rangeoshun** [comment]
Already fixed! :)
